language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - PROPHECY_VERSION=dev-master
  - PROPHECY_VERSION=~1.8.0
  - PROPHECY_VERSION=~1.7.0
  - PROPHECY_VERSION=~1.6.0
  - PROPHECY_VERSION=~1.5.0
  - PROPHECY_VERSION=~1.4.0
  - PROPHECY_VERSION=~1.3.0
  - PROPHECY_VERSION=~1.2.0
  - PROPHECY_VERSION=~1.1.0
  - PROPHECY_VERSION=~1.0.0

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer require phpspec/prophecy:${PROPHECY_VERSION} squizlabs/php_codesniffer phpmd/phpmd cundd/test-flight

script:
  - vendor/bin/phpunit
  - vendor/bin/test-flight README.md
  - vendor/bin/test-flight classes/
  - vendor/bin/phpcs --standard=PSR2 classes/ tests/
  - vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode
